apiVersion: v1
kind: Secret
metadata:
  name: navaar-secrets
  namespace: navaar
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
  NAVAAR_TELEGRAM_BOT_TOKEN: "REPLACE_ME"
  NAVAAR_YTMUSIC_CLIENT_ID: "REPLACE_ME"
  NAVAAR_YTMUSIC_CLIENT_SECRET: "REPLACE_ME"
